# 1.Print 'Hello HCIA'.

In [1]:
print("\'Hello HCIA\'")

'Hello HCIA'


# 2.Define two variables and calculate their sum.

In [2]:
a = 7
b = 3
a + b

10

# 3.Define a list and replicate in three different ways.

In [4]:
import copy

ls = [1, 2, 3, 4, 5]
ls_copy1 = ls[:]
ls_copy2 = copy.deepcopy(ls)
ls_copy3 = [num for num in ls]

ls.append(6)

print(ls)
print(ls_copy1)
print(ls_copy2)
print(ls_copy3)



[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


# 4.Define two lists and merge them together.

In [8]:
ls1 = [1,2,3]
ls2 = [4,5,6]

print(ls1 + ls2)


[1, 2, 3, 4, 5, 6]


# 5. Get the last element of the list and print it.

In [9]:
ls1[-1]

3

# 6.Define a tuple that contains only one element.

In [12]:
one_val_tup = (1, )
one_val_tup

(1,)

# 7.Define a three-line long string.

In [20]:
multistr = '''Hello
World
!'''


# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [21]:
tup_to_iter = (3,7,10)

for num in tup_to_iter:
    print(num)

3
7
10


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [22]:
def mul(a,b):
    return a * b

mul(8,6)

48

# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [1]:
import numpy as np

np.full([5,5],0)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [26]:
np.full([4,6],0)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [35]:
arr = np.arange(15,)
arr_reshaped = arr.reshape(3, 5)
print(arr)
print(arr_reshaped)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [2]:
m1 = np.full([5,5], 1)
m2 = np.full([5,5], 2)

np.add(m1, m2)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])