### 1、Import tensorflow and use tensorflow to define a constant.

In [3]:
import tensorflow as tf

a = tf.constant([1, 2, 3, 4, 5, 6])
a

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6])>

### 2、Use tensorflow to print 'Welcome to Huawei'.

In [4]:
tf.print('Welcome to Huawei')

Welcome to Huawei


### 3、Use tensorflow to define two numeric constants,then calculate them and print the result.

In [5]:
b = tf.constant([7,8,9,10,11,12])

tf.add(a, b)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 8, 10, 12, 14, 16, 18])>

### 4、Randomly generate two matrices using tensorflow, calculate and print the result of their multiplication.

In [6]:
g = tf.random.Generator.from_seed(1234)

m1 = g.normal(shape=(2, 3))
m2 = g.normal(shape=(2, 3))

tf.multiply(m1, m2)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.37096608,  0.9084582 ,  0.29024637],
       [-0.5672297 ,  1.3281987 , -0.07270187]], dtype=float32)>

### 5、Try to use your own handwriting number to do image recognition

In [10]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

predictions = model(x_train[:1]).numpy()
predictions

loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

loss_fn(y_train[:1], predictions).numpy()

model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 711us/step - loss: 0.2917 - accuracy: 0.9159
Epoch 2/5
1875/1875 [==============================] - 1s 694us/step - loss: 0.1424 - accuracy: 0.9579
Epoch 3/5
1875/1875 [==============================] - 1s 704us/step - loss: 0.1055 - accuracy: 0.9681
Epoch 4/5
1875/1875 [==============================] - 1s 700us/step - loss: 0.0889 - accuracy: 0.9729
Epoch 5/5
1875/1875 [==============================] - 1s 709us/step - loss: 0.0745 - accuracy: 0.9766


In [11]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0751 - accuracy: 0.9773


[0.07514145970344543, 0.9772999882698059]

In [20]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

probability_model(x_test[:1])

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[1.9348581e-08, 1.6024804e-10, 4.3914625e-07, 2.3456700e-05,
        1.7161904e-13, 2.8836837e-08, 2.5663288e-15, 9.9997532e-01,
        1.2383310e-07, 6.2291406e-07]], dtype=float32)>